species_1: "Human"
species_2: "Mouse"
organ: "Pancreas"

project_root: "/ocean/projects/bio230007p/jji5"

# For running HALPER (relative paths, make sure to set up the folder as instrcuted in the github repo.)
halper_repo: "tools/halLiftover-postprocessing"
hal_file: "data/Alignments/10plusway-master.hal"

species_1_peak_file: "data/Human_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"
species_2_peak_file: "data/Mouse_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"

halper_output_dir_htm: "output/halper/HtM"
halper_output_dir_mth: "output/halper/MtH"

halper_temp_dir: "output/halper/temp"

conda_env: "conda_envs/ATAC_env"

# For running bed
mapped_htm_file: "output/halper/HtM/idr.optimal_peak.HumanToMouse.HALPER.narrowPeak"
mouse_peak_file: "data/Mouse_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"

mapped_mth_file: "output/halper/MtH/idr.optimal_peak.MouseToHuman.HALPER.narrowPeak"
human_peak_file: "data/Human_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"

bed_output_dir_htm: "output/bed/HtM"
bed_output_dir_mth: "output/bed/MtH"

# TSS annotation files
mouse_tss_file: "data/MouseGenomeInfo/gencode.vM15.annotation.protTranscript.geneNames_TSSWithStrand_sorted.bed"
human_tss_file: "data/HumanGenomeInfo/gencode.v27.annotation.protTranscript.TSSsWithStrand_sorted.bed"

# Promoter/enhancer BED output folders
bed_pe_output_dir_htm: "output/bed_promoter_enhancer/HtM"
bed_pe_output_dir_mth: "output/bed_promoter_enhancer/MtH"

promoter_threshold: 2000

bed_g_temp_dir: "output/bed/temp"
bed_pe_temp_dir: "output/bed_pe/temp"


# For running rGREAT
rgreat_output_dir: "output/rgreat"
rgreat_temp_dir: "output/rgreat/temp"

rgreat:
  comparisons:
    HtM:
      genome_build: "mm10"
      shared_file: "output/bed/HtM/shared_ocrs.bed"
      species_specific_file: "output/bed/HtM/human_specific_ocrs.bed"
      base_outdir: "output/rgreat/HtM"

    MtH:
      genome_build: "hg38"
      shared_file: "output/bed/MtH/shared_ocrs.bed"
      species_specific_file: "output/bed/MtH/mouse_specific_ocrs.bed"
      base_outdir: "output/rgreat/MtH"

  full_species:
    Human:
      genome_build: "hg38"
      peak_file: "data/Human_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"
      base_outdir: "output/rgreat/Human"

    Mouse:
      genome_build: "mm10"
      peak_file: "data/Mouse_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"
      base_outdir: "output/rgreat/Mouse"

  slurm:
    partition: "RM-shared"
    time: "04:00:00"
    ntasks: 32
    mem: "8G"
    script_dir: "output/rgreat/temp"
    log_dir: "output/rgreat/logs"


# HOMER inputs
# Native species enhancer/promoter files
# Only keep these if your promoter/enhancer script actually outputs these files.
mouse_enhancer_file: "output/bed_promoter_enhancer/HtM/mouse_enhancer_ocrs.bed"
human_enhancer_file: "output/bed_promoter_enhancer/MtH/human_enhancer_ocrs.bed"

mouse_promoter_file: "output/bed_promoter_enhancer/HtM/mouse_promoter_ocrs.bed"
human_promoter_file: "output/bed_promoter_enhancer/MtH/human_promoter_ocrs.bed"

# Shared enhancer files
shared_enhancer_htm_file: "output/bed_promoter_enhancer/HtM/shared_enhancer_ocrs.bed"
shared_enhancer_mth_file: "output/bed_promoter_enhancer/MtH/shared_enhancer_ocrs.bed"

# Source-specific enhancer files
human_specific_enhancer_htm_file: "output/bed_promoter_enhancer/HtM/human_specific_enhancer_ocrs.bed"
mouse_specific_enhancer_mth_file: "output/bed_promoter_enhancer/MtH/mouse_specific_enhancer_ocrs.bed"

# Genome FASTA files
mouse_genome_fasta: "data/MouseGenomeInfo/mm10.fa"
human_genome_fasta: "data/HumanGenomeInfo/hg38.fa"

# HOMER output/temp folders
homer_output_dir: "output/homer"
homer_temp_dir: "output/homer/temp"
