# Base Setting
species_1: "Human"
species_2: "Mouse"
organ: "Pancreas"

# Halper Setting
halper_script: "/ocean/projects/bio230007p/jji5/tools/halLiftover-postprocessing/halper_map_peak_orthologs.sh"
hal_file: "/ocean/projects/bio230007p/jji5/data/Alignments/10plusway-master.hal"
halper_output_dir: "/ocean/projects/bio230007p/jji5/output/halper"
species_1_peak_file: "/ocean/projects/bio230007p/jji5/data/Human_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"
species_2_peak_file: "/ocean/projects/bio230007p/jji5/data/Mouse_Pancreas_ATAC/peak/idr_reproducibility/idr.optimal_peak.narrowPeak"

